// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_ma495.Models;

namespace Mission06_ma495.Migrations
{
    [DbContext(typeof(MovieSubmissionsContext))]
    [Migration("20230215182158_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_ma495.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Family",
                            Director = "Inigo Montoya",
                            Edited = false,
                            LentTo = "Mom",
                            Notes = "",
                            Rating = "PG",
                            Title = "The Princess Bride",
                            Year = "1987"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Family",
                            Director = "Mike Newell",
                            Edited = false,
                            LentTo = "Julia",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "The Guernsey Literary and Potato Peel Pie Society",
                            Year = "2018"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Schi-fi/Adventure",
                            Director = "Denis Villeneuve",
                            Edited = true,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Dune",
                            Year = "2021"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
