// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_ma495.Models;

namespace Mission06_ma495.Migrations
{
    [DbContext(typeof(MovieSubmissionsContext))]
    partial class MovieSubmissionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_ma495.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryID = 2,
                            Director = "Inigo Montoya",
                            Edited = false,
                            LentTo = "Mom",
                            Notes = "",
                            Rating = "PG",
                            Title = "The Princess Bride",
                            Year = "1987"
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryID = 1,
                            Director = "Mike Newell",
                            Edited = false,
                            LentTo = "Julia",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "The Guernsey Literary and Potato Peel Pie Society",
                            Year = "2018"
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryID = 1,
                            Director = "Denis Villeneuve",
                            Edited = true,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Dune",
                            Year = "2021"
                        });
                });

            modelBuilder.Entity("Mission06_ma495.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Comedy"
                        });
                });

            modelBuilder.Entity("Mission06_ma495.Models.ApplicationResponse", b =>
                {
                    b.HasOne("Mission06_ma495.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
